# Generated by Django 6.0.2 on 2026-05-01 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemQuality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quality", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="item",
            name="item_quality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Core.itemquality"
            ),
        ),
    ]
