# Generated by Django 6.0.2 on 2026-05-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_quality',
            field=models.CharField(choices=[('3', 'New'), ('2', 'Good'), ('1', 'Used')], default='1'),
        ),
    ]
