# Generated by Django 6.0.2 on 2026-05-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0002_alter_item_item_quality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_quality",
            field=models.CharField(
                choices=[
                    ("4", "Mint"),
                    ("3", "Very Good"),
                    ("2", "Good"),
                    ("1", "Fair"),
                ],
                default="3",
                max_length=1,
            ),
        ),
    ]
